author:
  name: Troy Cherasaro
baseURL: /
languageCode: en
menu:
  main:
    - name: About
      url: /about
params:
  description: Example site for the Hugo's Blogpaper theme
title: Troy Cherasaro
theme: Blogpaper
